#!/bin/bash
REPOS="$1"
REV="$2"
#文件需要指明环境变量

#中文设置此配置
export LANG=en_US.UTF-8
LOGPATH="/app/log"

[ -d "$LOGPATH" ] && mkdir -p ${LOGPATH}

SVN=/usr/bin/svn
#必须先检出svn到/data/www目录
#可以去掉用户名和密码
$SVN update --username=lizhen --password=lizhen /data/www
if [ $? -eq 0 ]
then
  /usr/bin/rsync -az --delete /data/www /tmp/
fi
