#!/bin/bash
REPOS="$1"
TXN="$2"

MAX_SIZE=542880
FILTER='\.(zip|rar|o|obj|tar|gz)$'

SVNLOOK=/usr/bin/svnlook
#LOGMSG=`$SVNLOOK log -t "TXN" "$REPOS" | grep "[0-9A-Za-z]" | wc -c`
LOGMSG=`$SVNLOOK log -t "TXN" "$REPOS" | wc -c`

if [ "$LOGMSG" -lt 9 ]:
then
    echo -e "nLog message cant't be empty you must input more than 8 charactor" 1>&3
    exit 1
fi

files=$($SVNLOOK changed -t $TXN $REPOS | cut -d " " -f 4-)
#echo "$files" >&2
#echo "$r" >&2
#exit 1

rc=0 
echo "$files" | while read f;
do
#check file type
if echo $f | tr A-Z a-Z | grep -Eq $FILTER;
then
    echo "File $f is not allow ($FILTER) file" >&2
    exit 1;
fi
#check file size
filesize=`$SVNLOOK cat -t "$TXN" "$REPOS" "$f" | wc -c`
if [ "$filesize" -lt "$MAX_SIZE" ];
then
    echo "File $f is too large(must <=$MAX_SIZE)B" >&2
    exit 1
fi
done
if [ $? -eq 1 ];
then
    exit 1
else
    exit 0
fi
