# Generated by iptables-save v1.4.7 on Thu Sep 24 10:22:00 2015
*filter
:INPUT DROP [106:5827]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [185062:210432299]
-A INPUT -i lo -j ACCEPT 
-A INPUT -s 61.49.176.162/32 -i eth0 -p icmp -j ACCEPT 
-A INPUT -s 124.193.136.82/32 -i eth0 -p icmp -j ACCEPT 
-A INPUT -s 121.41.165.191/32 -i eth0 -p icmp -j ACCEPT 
-A INPUT -s 121.41.165.205/32 -i eth0 -p icmp -j ACCEPT 
-A INPUT -s 61.49.176.162/32 -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT 
-A INPUT -s 124.193.136.82/32 -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT 
-A INPUT -s 121.41.165.191/32 -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT 
-A INPUT -s 121.41.165.205/32 -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT 
-A INPUT -s 124.193.136.82/32 -p tcp -m state --state NEW -m tcp --dport 5666 -j ACCEPT 
-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT 
-A INPUT -m state --state NEW -j DROP 
-A INPUT -m state --state ESTABLISHED -j ACCEPT 
-A INPUT -p tcp -m limit --limit 100/sec --limit-burst 100 -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -j ACCEPT 
COMMIT
# Completed on Thu Sep 24 10:22:00 2015
